"""add additional info to JobTask

Revision ID: 704e96f09d22
Revises: f7f8002f0734
Create Date: 2026-07-11 19:00:38.502048

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "704e96f09d22"
down_revision: Union[str, Sequence[str], None] = "f7f8002f0734"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_tasks",
        sa.Column("report_object_name", sa.String(), nullable=True),
    )
    op.add_column("job_tasks", sa.Column("result", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_tasks", "result")
    op.drop_column("job_tasks", "report_object_name")
    # ### end Alembic commands ###
